AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Apache Tika Serverless Text Extracter

Parameters:
    DocumentBucketName:
        Type: String
        Description: S3 bucket into which new documents are uploaded
    SourcePrefix:
        Type: String
        Description: Prefix for document upload
        Default: "upload/"
    TargetPrefix:
        Type: String
        Description: Prefix for extracted data
        Default: "extracted/"
    TargetExtension:
        Type: String
        Description: File extension for extracted data
        Default: ".extracted.json"

Globals:
    Function:
        Tracing: Active

Resources:

    DocumentBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref DocumentBucketName

    TikaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: build/distributions/tika-lambda.zip
            Handler: extractor.TikaLambdaHandler::handleRequest
            Runtime: java8
            Timeout: 60
            MemorySize: 512
            Events:
                FileUploaded:
                    Type: S3
                    Properties:
                        Bucket: !Ref DocumentBucket
                        Events: s3:ObjectCreated:*
                        Filter:
                            S3Key:
                                Rules:
                                    - Name: prefix
                                      Value: !Ref SourcePrefix
            Policies:
                - AWSLambdaExecute
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - s3:GetObject
                        - s3:GetObjectACL
                      Resource: !Sub arn:aws:s3:::${DocumentBucketName}/${SourcePrefix}*
                    - Effect: Allow
                      Action:
                        - s3:PutObject
                      Resource: !Sub arn:aws:s3:::${DocumentBucketName}/${TargetPrefix}*
            Environment:
                Variables:
                    S3_SOURCE_PREFIX: !Ref SourcePrefix
                    S3_TARGET_PREFIX: !Ref TargetPrefix
                    S3_TARGET_EXT: !Ref TargetExtension